# Template inclusion
include:
  - project: 'devops/templates'
    ref: $CI_COMMIT_REF_NAME 
    file: 'ci-template.yml'

# Job definition 
build: 
  extends: .build-template 
 
test: 
  extends: .test-template 
 
package: 
  extends: .package-template 
 
docker-build: 
  extends: .docker-template 
  only: 
    - main