services:
  mysql-db:
    env_file:
      - .env_prod
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  mongodb:
    env_file:
      - .env_prod
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

  product_management1:
    env_file:
      - .env_prod
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE_ACTIVE}
      APP_DATABASE: ${ACTIVE_DB}
      SPRING_DATASOURCE_URL: "jdbc:mysql://product-management-db-c1/${DB_NAME}"
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: 8080
      SERVER_ENV_DEV_ADDRESS: ${VM_IP}
      SERVER_ENV_DEV_PORT: 80
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_MONGODB_URI: "mongodb://mongodb:27017/${MONGO_DB}"

  product_management2:
    env_file:
      - .env_prod
    environment:
      SPRING_PROFILES_ACTIVE: prod
      APP_DATABASE: ${ACTIVE_DB}
      SPRING_DATASOURCE_URL: "jdbc:mysql://product-management-db-c1/${DB_NAME}"
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: 8080
      SERVER_ENV_DEV_ADDRESS: ${VM_IP}
      SERVER_ENV_DEV_PORT: 80
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_MONGODB_URI: ${MONGODB_URI}