services:
  mysql-db:
    env_file:
      - .env_dev
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  mongodb:
    env_file:
      - .env_dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

  mongo-express:
    env_file:
      - .env_dev
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_ADMIN_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_ADMIN_PASSWORD}

  redis:
    env_file:
      - .env_dev
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  product_management1:
    env_file:
      - .env_dev
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE_ACTIVE}
      APP_DATABASE: ${ACTIVE_DB}
      SPRING_DATASOURCE_URL: "jdbc:mysql://product-management-db-c1/${DB_NAME}"
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: 8080
      SERVER_ENV_DEV_ADDRESS: ${VM_IP}
      SERVER_ENV_DEV_PORT: 80
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD}
      SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE: ${MONGODB_AUTHENTICATION_DATABASE}
      SPRING_DATA_MONGODB_HOST: ${MONGODB_HOST}
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: ${MONGODB_DATABASE}
      SPRING_DATA_MONGODB_USERNAME: ${MONGODB_USERNAME}
      SPRING_DATA_MONGODB_PASSWORD: ${MONGODB_PASSWORD}

  product_management2:
    env_file:
      - .env_dev
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE_ACTIVE}
      APP_DATABASE: ${ACTIVE_DB}
      SPRING_DATASOURCE_URL: "jdbc:mysql://product-management-db-c1/${DB_NAME}"
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: 8080
      SERVER_ENV_DEV_ADDRESS: ${VM_IP}
      SERVER_ENV_DEV_PORT: 80
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD}
      SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE: ${MONGODB_AUTHENTICATION_DATABASE}
      SPRING_DATA_MONGODB_HOST: ${MONGODB_HOST}
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: ${MONGODB_DATABASE}
      SPRING_DATA_MONGODB_USERNAME: ${MONGODB_USERNAME}
      SPRING_DATA_MONGODB_PASSWORD: ${MONGODB_PASSWORD}
