services:
  product_management1:
    env_file:
      - .env_prod
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE_ACTIVE}
      SPRING_DATASOURCE_URL: "jdbc:mysql://product-management-db-c1/${DB_NAME}"
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: 8080
      SERVER_ENV_DEV_ADDRESS: ${VM_IP}
      SERVER_ENV_DEV_PORT: 80
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}

  product_management2:
    env_file:
      - .env_prod
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: "jdbc:mysql://product-management-db-c1/${DB_NAME}"
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: 8080
      SERVER_ENV_DEV_ADDRESS: ${VM_IP}
      SERVER_ENV_DEV_PORT: 80
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
    depends_on:
      mysql-db:
        condition: service_healthy