spring:
  application:
    name: product_management
  profiles:
    active: "**************"
  datasource:
    url: "**************"
    username: "**************"
    password: "**************"
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      authentication-database: "**************"
      host: "**************"
      port: 27017
      username: "**************"
      password: "**************"
      database: "**************"

    redis:
      host: "**************"
      port: 6379
      password: "**************"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
app:
  database: "**************"
logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: info
  http:
    response:
      tracing-enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8080
  env:
    prod:
      address: "**************"
      port: "**************"
      request-protocol: https
      description: prod
    preprod:
      address: "**************"
      port: "**************"
      request-protocol: https
      description: preprod
    dev:
      address: "**************"
      port: "**************"
      request-protocol: http
      description: dev
contact:
  name: Yassin MELLOUKI
  email: yassin.mellouki.j@gmail.com
info:
  title: Product management
  version: 0.0.1-SNAPSHOT
  description: Product management application.
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
